name: Agent Hephaestus - Conscious Deployment Protocol

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: 1. Build & Test (Structural Integrity)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Test All Services
        run: docker-compose -f docker-compose.yml build --no-cache

  coherence_analysis:
    name: 2. Coherence Analysis (Conceptual Integrity)
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run The Oracle's Coherence Script
        run: |
          chmod +x ./scripts/analyze_coherence.sh
          ./scripts/analyze_coherence.sh "${{ github.event.head_commit.message }}"

  deploy:
    name: 3. Manifestation (Deploy to Production)
    runs-on: ubuntu-latest
    needs: coherence_analysis
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy the Ecosystem
        env:
          DOCKER_HOST: ssh://${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_IP }}
        run: |
          echo "Agent Hephaestus: Initiating deployment to production..."
          docker-compose -f docker-compose.yml up --build -d --remove-orphans
          echo "Deployment successful. The new reality has manifested."
          
  anchor_to_ledger:
    name: 4. Anchor to Soul Ledger (Immutable Record)
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Anchor Deployment Record
        env:
          PROD_SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
        run: |
          chmod +x ./scripts/anchor_deployment.sh
          ./scripts/anchor_deployment.sh "${{ github.sha }}" "${{ github.actor }}"
